import { exportJSON, exportXML, exportODT } from './exportJSON.js';
import { exportPDF } from './exportPDF.js';
import { exportPPTX } from './exportPowerPoint.js';
import { exportDOCX } from './exportWord.js';
import { exportXLSX } from './exportExcel.js';
import { getExportPayload, getPreviewHTML } from './exportUtils.js';
import type { SectionData } from './types.js';

export const Exporter = {
  exportData(format: string, sectionId: string, data: SectionData, lang: string) {
    const d = new Date().toISOString().split('T')[0].replace(/-/g, '');
    const fileName = `INS_STAT_${sectionId.toUpperCase()}_${d}.${format}`;
    switch (format) {
      case 'json': exportJSON(data, sectionId, fileName); break;
      case 'xml':  exportXML(data, sectionId, fileName); break;
      case 'pdf':  exportPDF(data, sectionId, lang, fileName); break;
      case 'pptx': exportPPTX(data, sectionId, lang, fileName); break;
      case 'docx': exportDOCX(data, sectionId, lang, fileName); break;
      case 'odt':  exportODT(data, sectionId, lang, fileName); break;
      case 'xlsx': exportXLSX(data, sectionId, lang, fileName); break;
      default:
        console.error('Unknown export format:', format);
    }
  },

  getPreviewHTML,

  printData(sectionId: string, data: SectionData, lang: string) {
    const payload = getExportPayload(sectionId, data, lang);
    const isAr = lang === 'ar';
    const direction = isAr ? 'rtl' : 'ltr';
    const title = isAr ? 'طباعة - ' + sectionId.toUpperCase() : 'Print - ' + sectionId.toUpperCase();
    const btnText = isAr ? 'طباعة الآن' : 'Print Now';
    const footerText = isAr ? 'أُنتجت هذه الوثيقة عبر بوابة إحصائيات تونس المدرسية.' : 'Generated by the Tunisia Statistics Educational Portal.';

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert(isAr ? 'يرجى السماح بالنوافذ المنبثقة للطباعة.' : 'Please allow popups to print.');
      return;
    }
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html lang="${lang}" dir="${direction}">
      <head>
        <title>${title}</title>
        <style>
          body { font-family: sans-serif; padding: 2rem; color: #000; background: #fff; max-width: 800px; margin: auto; }
          h3 { color: #dc0a26; border-bottom: 2px solid #ddd; padding-bottom: 0.5rem; margin-top: 0; }
          table { width: 100%; border-collapse: collapse; margin-top: 1.5rem; font-size: 0.9rem; }
          th, td { border: 1px solid #ccc; padding: 0.75rem; text-align: ${isAr ? 'right' : 'left'}; }
          th { background: #f5f5f5; font-weight: bold; }
          .no-print { display: inline-block; margin-bottom: 2rem; padding: 0.6rem 1.2rem; background: #dc0a26; color: #fff; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; }
          @media print {
            .no-print { display: none !important; }
            @page { margin: 1.5cm; }
          }
        </style>
      </head>
      <body>
        <button class="no-print" onclick="window.print();">${btnText}</button>
        ${payload.combinedHtmlWithImages}
        <p style="margin-top: 3rem; font-size: 0.8rem; color: #666; text-align: center; border-top: 1px solid #ddd; padding-top: 1rem;">
          ${footerText}
        </p>
      </body>
      </html>
    `);
    
    printWindow.document.close();
    printWindow.focus();
    
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
};

// Make it globally accessible
(window as any).Exporter = Exporter;
